// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetRentalByID(ctx context.Context, id int32) (GetRentalByIDRow, error)
	GetRentals(ctx context.Context, arg GetRentalsParams) ([]GetRentalsRow, error)
}

var _ Querier = (*Queries)(nil)
